name: PR-Buddy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install flake8
      - run: flake8 . --exit-zero --format=default > lint.txt
      - uses: actions/upload-artifact@v4
        with: { name: lint , path: lint.txt }

  review:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: lint , path: . }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install "openai==0.28" PyGithub requests
      - id: prbuddy
        run: python prbuddy/review.py
        env:
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER:       ${{ github.event.pull_request.number }}
      - name: Result summary
        run: echo "${{ steps.prbuddy.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
